export enum Property {
  ALIGN_ITEMS = "align-items",
  BACKGROUND = "background",
  BORDER_RADIUS = "border-radius",
  BOX_SHADOW = "box-shadow",
  BOX_SIZING = "box-sizing",
  COLOR = "color",
  CURSOR = "cursor",
  DISPLAY = "display",
  FONT_SIZE = "font-size",
  GRID_TEMPLATE_COLUMNS = "grid-template-columns",
  GRID_TEMPLATE_ROWS = "grid-template-rows",
  JUSTIFY_CONTENT = "justify-content",
  LINE_HEIGHT = "line-height",
  LIST_STYLE_TYPE = "list-style-type",
  MARGIN_BLOCK_START = "margin-block-start",
  MARGIN_BLOCK_END = "margin-block-end",
  MAX_WIDTH = "max-width",
  MAX_HEIGHT = "max-height",
  MIN_WIDTH = "min-width",
  MIN_HEIGHT = "min-height",
  PADDING_INLINE_START = "padding-inline-start",
  POSITION = "position",
  TEXT_ALIGN = "text-align",
  Z_INDEX = "z-index",
}

export enum PropertyName {
  ALIGN_ITEMS,
  BACKGROUND,
  BORDER_RADIUS,
  BOX_SHADOW,
  BOX_SIZING,
  COLOR,
  CURSOR,
  DISPLAY,
  FONT_SIZE,
  GRID_TEMPLATE_COLUMNS,
  GRID_TEMPLATE_ROWS,
  JUSTIFY_CONTENT,
  LINE_HEIGHT,
  LIST_STYLE_TYPE,
  MARGIN_BLOCK_START,
  MARGIN_BLOCK_END,
  MAX_WIDTH,
  MAX_HEIGHT,
  MIN_WIDTH,
  MIN_HEIGHT,
  PADDING_INLINE_START,
  POSITION,
  TEXT_ALIGN,
  Z_INDEX,
}

export const COLON = ":";

export const PROPERTY_MAP = new Map<PropertyName, string>([
  [PropertyName.ALIGN_ITEMS, Property.ALIGN_ITEMS],
  [PropertyName.BACKGROUND, Property.BACKGROUND],
  [PropertyName.BORDER_RADIUS, Property.BORDER_RADIUS],
  [PropertyName.BOX_SHADOW, Property.BOX_SHADOW],
  [PropertyName.BOX_SIZING, Property.BOX_SIZING],
  [PropertyName.COLOR, Property.COLOR],
  [PropertyName.CURSOR, Property.CURSOR],
  [PropertyName.DISPLAY, Property.DISPLAY],
  [PropertyName.FONT_SIZE, Property.FONT_SIZE],
  [PropertyName.GRID_TEMPLATE_COLUMNS, Property.GRID_TEMPLATE_COLUMNS],
  [PropertyName.GRID_TEMPLATE_ROWS, Property.GRID_TEMPLATE_ROWS],
  [PropertyName.JUSTIFY_CONTENT, Property.JUSTIFY_CONTENT],
  [PropertyName.LINE_HEIGHT, Property.LINE_HEIGHT],
  [PropertyName.LIST_STYLE_TYPE, Property.LIST_STYLE_TYPE],
  [PropertyName.MARGIN_BLOCK_START, Property.MARGIN_BLOCK_START],
  [PropertyName.MARGIN_BLOCK_END, Property.MARGIN_BLOCK_END],
  [PropertyName.MAX_WIDTH, Property.MAX_WIDTH],
  [PropertyName.MAX_HEIGHT, Property.MAX_HEIGHT],
  [PropertyName.MIN_WIDTH, Property.MIN_WIDTH],
  [PropertyName.MIN_HEIGHT, Property.MIN_HEIGHT],
  [PropertyName.PADDING_INLINE_START, Property.PADDING_INLINE_START],
  [PropertyName.POSITION, Property.POSITION],
  [PropertyName.TEXT_ALIGN, Property.TEXT_ALIGN],
  [PropertyName.Z_INDEX, Property.Z_INDEX],
]);
