name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.12.0'

    - name: Use npm 11.6.2
      run: npm i -g npm@11.6.2

    - name: Show runtime versions
      run: node -v && npm -v

    - name: cache npm
      uses: actions/cache@v4
      with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: cache playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    
    - name: npm ci
      run: npm ci
    
    - name: install playwright dependencies
      run: npx playwright install --with-deps chromium

    - name: npm run build
      run: npm run build

    - name: npm test
      run: npm test
